#  Even Fibonacci numbers

#  Each new term in the Fibonacci sequence is generated by adding the previous two terms.
#  By starting with 1 and 2, the first 10 terms will be:
#  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#  x(i) = x(i-1) + x(i-2)
#  By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

def find_the_sum_of_the_evens (limit)
  i0 = 0
  i1 = 1
  i2 = 0
  sum = 0
  limit.times do
    i2 = i0 + i1
    if i2 < limit
      i0 = i1
      i1 = i2
      sum += i2
    end
  end
  puts sum
end

find_the_sum_of_the_evens 4000000

